/**
 * EntityGroup contains entities of same type. In principle, EntityGroup is
 * nothing more than an allocation table; it just specifies list of components
 * and the offset of each component.
 */
export class EntityGroup {
  size: number = 0;

  maxSize: number = 0;

  /**
   * Offset of each component. If the component is not present in EntityGroup,
   * '-1' is specified.
   */
  offsets: number[] = [];

  // EntityGroup don't do anything more than this... for now. Utility functions
  // will be provided using 'EntityGroupHandle', which is generated by
  // the engine (EntityStore)
}
